name: Rust

on:
  push:
    branches: ["master"]
    

env:
  CARGO_TERM_COLOR: always

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run tests
        run: |
          cd rust-api
          cargo tarpaulin --out xml --skip-clean --fail-immediately

      - name: Upload to codecov
        run: |
          curl -Os https://cli.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov do-upload -F rust-api -t ${{secrets.CODECOV_TOKEN}}

  smart-contract-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Run tests
        env:
          TESTNET_ENDPOINT: https://testnet.hashio.io/api
          TESTNET_OPERATOR_PRIVATE_KEY: '0xd14cfce33a5056431635f8dcd0b685161524ea81ceeada09fc2b66c15444ca31'
          LOCAL_OPERATOR_PRIVATE_KEY: '0xd14cfce33a5056431635f8dcd0b685161524ea81ceeada09fc2b66c15444ca31'
        run: |
          cd smart-contract
          npm i
          npm run coverage

      - name: Upload to codecov
        run: |
          curl -Os https://cli.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov do-upload -F smart-contract -t ${{secrets.CODECOV_TOKEN}}